con <- file("ajps.log")
sink(con, append=TRUE)
sink(con, append=TRUE, type="message")

source("Figure_1_map.R",echo = T)
source("Figure_2_providerssubscribers.R",echo = T)
source("Table1.R",echo = T)
source("Table2.R",echo = T)
source("Figure_3_comscoreproviders.R",echo = T)
source("Figure_4_nes.R",echo = T)
source("FigA1.R",echo = T)
source("ROW Validation Checks.R",echo = T)
source("figc1.R",echo = T)
source("tablec1.R",echo = T)
source("tablese3e4.R",echo = T)
sink() 
sink(type="message")
